### ISSUE TITLE
Add help at the command-line

### ISSUE THREAD

**Issue by evjan** [roodi/roodi#29]
You should be able to run `roodi -h` or `roodi --help`

**Comment by sylvestre** [comment]
Yeh, that would help us (Debian) too

**Comment by clemux** [comment]
Indeed. Also: adding a -v or --version argument thats prints roodi's version would be very helpful. For example, when writing a wrapper around roodi.

**Comment by evjan** [comment]
@sylvestre How do you mean, is that something that would help Debian more than others?
@clemux Yeah, that should be easy enough to add. Care to submit a PR? ;)

**Comment by evjan** [comment]
Added both -h and -v in Roodi 5.0.0, commit 01316310ae128a4c7813f47d636123b3508f7a38
