### ISSUE TITLE
RuntimeError with Ruby 2.3

### ISSUE THREAD

**Issue by mcandre** [roodi/roodi#36]
Source:

https://github.com/mcandre/mcandre/tree/master/ruby

Trace:

```
bundle exec roodi -config=roodi.yml *.rb **/*.rb

Running Roodi checks
ccard/ccard.rb:62 - Method "main" has 52 lines.  It should have 50 or less.
tiny/tiny.rb:111 - Method "main" has 51 lines.  It should have 50 or less.

Checked 47 files
/Users/andrew.pennebaker/.gem/ruby/2.3.0/gems/roodi-4.1.1/lib/roodi/core/runner.rb:52:in `output_result': Found 2 errors. (RuntimeError)
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/gems/roodi-4.1.1/lib/roodi/core/runner.rb:41:in `start'
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/gems/roodi-4.1.1/bin/roodi:13:in `<top (required)>'
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/bin/roodi:23:in `load'
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/bin/roodi:23:in `<main>'
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/andrew.pennebaker/.gem/ruby/2.3.0/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
Command failed with status (1): [bundle exec roodi -config=roodi.yml *.rb *...]
```

System:
- Ruby 2.3
- chruby
- rvm
- Mac OS X El Capitan 10.11.2

**Comment by evjan** [comment]
Wow, this issue has been here a long time. Is it still a problem?

**Comment by evjan** [comment]
Closing due to lack of input

**Comment by elik-ru** [comment]
This is still a problem

roodi finds any problem with code an exception is thrown in lib/roodi/core/runner.rb:52
and a stack trace is printed

last version (5.0.0) has same problem. 

This is quite confusing.

**Comment by evjan** [comment]
@elik-ru yeah, I don't know why it doesn't just exit with a non-zero status code instead

**Comment by davearonson** [comment]
It does both, sorta -- though I don't think it will get to the usual exit path if it first raises!  I've just submitted a PR to let you optionally not make it raise.  (A problem I discovered separately before seeing this issue.)
